# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='activity',
            field=models.ManyToManyField(blank=True, to='search.CourseType'),
        ),
        migrations.AddField(
            model_name='payment',
            name='child',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Child'),
        ),
        migrations.AddField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='search.Course'),
        ),
        migrations.AddField(
            model_name='child',
            name='attend_to',
            field=models.ManyToManyField(related_name='child_course', through='authentication.Payment', to='search.Course'),
        ),
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.UserProfile'),
        ),
        migrations.AddField(
            model_name='child',
            name='prev_activities',
            field=models.ManyToManyField(blank=True, to='search.CourseType'),
        ),
    ]
