# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160713141539 on 2016-08-14 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20160813_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='several',
            field=models.BooleanField(default=False),
        ),
    ]
