# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160713141539 on 2016-08-21 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_question_yesno'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(blank=True, default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='nameCompany',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='sex',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='siteCompany',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='surname',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
