# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160713141539 on 2016-08-21 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20160821_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='sex',
        ),
    ]
