# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160713141539 on 2016-08-21 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_userinfo_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='sex',
            field=models.IntegerField(default=0),
        ),
    ]
