# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160713141539 on 2016-08-23 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20160822_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(choices=[('M', 'мальчик'), ('W', 'девочка')], default=None, max_length=2),
        ),
    ]
