# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160713141539 on 2016-08-24 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_auto_20160824_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
