# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160713141539 on 2016-07-21 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20160716_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('title', models.CharField(max_length=128)),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='level',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='search.Level'),
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='skill',
            field=models.ManyToManyField(blank=True, to='search.Skill'),
        ),
    ]
