# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160713141539 on 2016-07-26 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20160721_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='introtext',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, max_length=16384),
        ),
    ]
