# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160713141539 on 2016-07-27 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20160726_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinfo',
            name='activity',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='search.CourseType'),
        ),
    ]
