# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160713141539 on 2016-07-29 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_courseinfo_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
