# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160713141539 on 2016-08-12 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_course_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='coordinate_x',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='coordinate_y',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='search.Level'),
        ),
    ]
