# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160713141539 on 2016-08-21 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_course_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinfo',
            name='price',
        ),
    ]
