# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160713141539 on 2016-08-24 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_remove_courseinfo_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='moderation',
            field=models.BooleanField(default=False),
        ),
    ]
