# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160713141539 on 2016-08-27 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0012_course_moderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='metro',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
