# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160713141539 on 2016-08-27 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0014_remove_course_metro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinfo',
            name='location',
        ),
    ]
