# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160713141539 on 2016-08-27 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0015_remove_courseinfo_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='location',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='search.Metro'),
        ),
    ]
